//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_USER
    {
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL { get; set; }
        public string ROLE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> LOGIN_ATTEMPT { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
        public string ENTER_USER { get; set; }
        public Nullable<int> REF_ID { get; set; }
        public string PIC { get; set; }
    }
}
