//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAREGIVER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAREGIVER()
        {
            this.FEEDBACKS = new HashSet<FEEDBACK>();
            this.CAREGIVER_ASSIGN_ELDER = new HashSet<CAREGIVER_ASSIGN_ELDER>();
        }
    
        public int ID { get; set; }
        public string CAREGIVER_CODE { get; set; }
        public string FULL_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string NIC { get; set; }
        public string CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string PROFILE_IMG { get; set; }
        public string HIGHER_QULIFICATION { get; set; }
        public Nullable<int> YEAR_OF_EXPERIENCE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
        public string ENTER_BY { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAREGIVER_ASSIGN_ELDER> CAREGIVER_ASSIGN_ELDER { get; set; }
    }
}
