//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAREGIVER_ASSIGN_ELDER
    {
        public int ID { get; set; }
        public Nullable<int> CAREGIVER_ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public string ROLE { get; set; }
        public string ASSIGNED_BY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual CAREGIVER CAREGIVER { get; set; }
        public virtual ELDER ELDER { get; set; }
    }
}
