//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public int ID { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string EMAIL { get; set; }
        public string EMAIL_PASSWORD { get; set; }
        public string WEBSITE { get; set; }
    }
}
