//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTOR()
        {
            this.ELDER_CHECKUP = new HashSet<ELDER_CHECKUP>();
            this.GLUCODE_READING = new HashSet<GLUCODE_READING>();
            this.MEAL_PLANS = new HashSet<MEAL_PLANS>();
        }
    
        public int ID { get; set; }
        public string D_CODE { get; set; }
        public string FULL_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SPECIALIZATION { get; set; }
        public string MEDICAL_LICENSE_NO { get; set; }
        public string CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string REGISTERED_HOSPITAL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> JOINED_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PROFILE_IMAGE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELDER_CHECKUP> ELDER_CHECKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLUCODE_READING> GLUCODE_READING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL_PLANS> MEAL_PLANS { get; set; }
    }
}
