//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONETION_EVENT_ITEMS
    {
        public int ID { get; set; }
        public Nullable<int> DONETION_EVENT_ID { get; set; }
        public Nullable<int> GROCERY_ID { get; set; }
        public Nullable<decimal> QTY_IN_GRAMS { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual DONETION_EVENT DONETION_EVENT { get; set; }
        public virtual GROCERY_ITEMS GROCERY_ITEMS { get; set; }
    }
}
