//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ELDER_NUTRICIANTSEntities : DbContext
    {
        public ELDER_NUTRICIANTSEntities()
            : base("name=ELDER_NUTRICIANTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAREGIVER> CAREGIVERs { get; set; }
        public virtual DbSet<DOCTOR> DOCTORs { get; set; }
        public virtual DbSet<DONETION_EVENT> DONETION_EVENT { get; set; }
        public virtual DbSet<DONETION_EVENT_ITEMS> DONETION_EVENT_ITEMS { get; set; }
        public virtual DbSet<ELDER> ELDERs { get; set; }
        public virtual DbSet<ELDER_CHECKUP> ELDER_CHECKUP { get; set; }
        public virtual DbSet<ELDER_GURDIAN> ELDER_GURDIAN { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACKS { get; set; }
        public virtual DbSet<GLUCODE_READING> GLUCODE_READING { get; set; }
        public virtual DbSet<GLUCOSE_READING_REPORT> GLUCOSE_READING_REPORT { get; set; }
        public virtual DbSet<GROCERY_ITEM_NUTRICIANTS> GROCERY_ITEM_NUTRICIANTS { get; set; }
        public virtual DbSet<GROCERY_ITEMS> GROCERY_ITEMS { get; set; }
        public virtual DbSet<HEALTH_ALERT> HEALTH_ALERT { get; set; }
        public virtual DbSet<HEALTH_PREDICTION> HEALTH_PREDICTION { get; set; }
        public virtual DbSet<INCREAMENT> INCREAMENTs { get; set; }
        public virtual DbSet<MDCODE> MDCODEs { get; set; }
        public virtual DbSet<MEAL_PLANS> MEAL_PLANS { get; set; }
        public virtual DbSet<MEAL_PLANS_ITEMS> MEAL_PLANS_ITEMS { get; set; }
        public virtual DbSet<ROOM_ASSIGNED> ROOM_ASSIGNED { get; set; }
        public virtual DbSet<ROOM> ROOMS { get; set; }
        public virtual DbSet<APP_USER> APP_USER { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<V_ELDER> V_ELDER { get; set; }
        public virtual DbSet<V_ELDER_BLOOD_RPT> V_ELDER_BLOOD_RPT { get; set; }
        public virtual DbSet<CAREGIVER_ASSIGN_ELDER> CAREGIVER_ASSIGN_ELDER { get; set; }
        public virtual DbSet<V_ASSIGN_CAREGIVER> V_ASSIGN_CAREGIVER { get; set; }
        public virtual DbSet<V_ASSIGN_ROOMS> V_ASSIGN_ROOMS { get; set; }
        public virtual DbSet<ELDER_DEATH> ELDER_DEATH { get; set; }
        public virtual DbSet<GROCERY_ITEM_CATEGORY> GROCERY_ITEM_CATEGORY { get; set; }
        public virtual DbSet<V_MEALS> V_MEALS { get; set; }
    
        public virtual ObjectResult<string> PROC_INCREMENT_ID(string tYPE)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_INCREMENT_ID", tYPEParameter);
        }
    
        public virtual ObjectResult<string> PROC_INCREMENT_ID_UPADATE(string tYPE)
        {
            var tYPEParameter = tYPE != null ?
                new ObjectParameter("TYPE", tYPE) :
                new ObjectParameter("TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PROC_INCREMENT_ID_UPADATE", tYPEParameter);
        }
    }
}
