//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELDER_CHECKUP
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public Nullable<System.DateTime> CHECKUP_DATE { get; set; }
        public string PURPOSE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> NEXT_FOLLOW_UP_DATE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ELDER ELDER { get; set; }
    }
}
