//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELDER()
        {
            this.ELDER_CHECKUP = new HashSet<ELDER_CHECKUP>();
            this.ELDER_GURDIAN = new HashSet<ELDER_GURDIAN>();
            this.FEEDBACKS = new HashSet<FEEDBACK>();
            this.GLUCODE_READING = new HashSet<GLUCODE_READING>();
            this.GLUCOSE_READING_REPORT = new HashSet<GLUCOSE_READING_REPORT>();
            this.HEALTH_ALERT = new HashSet<HEALTH_ALERT>();
            this.HEALTH_PREDICTION = new HashSet<HEALTH_PREDICTION>();
            this.MEAL_PLANS = new HashSet<MEAL_PLANS>();
            this.ROOM_ASSIGNED = new HashSet<ROOM_ASSIGNED>();
            this.CAREGIVER_ASSIGN_ELDER = new HashSet<CAREGIVER_ASSIGN_ELDER>();
            this.ELDER_DEATH = new HashSet<ELDER_DEATH>();
        }
    
        public int ID { get; set; }
        public string ELDER_CODE { get; set; }
        public string FULL_NAME { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public string CONTACT_NO { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<int> IS_DEAD { get; set; }
        public string PROFIL_PIC { get; set; }
        public string ROOM_NUMBER { get; set; }
        public Nullable<decimal> CURRENT_SUGAR_LEVEL { get; set; }
        public Nullable<System.DateTime> CURRENT_SUGAR_LEVEL_ENTER_DATE { get; set; }
        public Nullable<int> IS_DIABITCS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELDER_CHECKUP> ELDER_CHECKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELDER_GURDIAN> ELDER_GURDIAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEEDBACK> FEEDBACKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLUCODE_READING> GLUCODE_READING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLUCOSE_READING_REPORT> GLUCOSE_READING_REPORT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEALTH_ALERT> HEALTH_ALERT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEALTH_PREDICTION> HEALTH_PREDICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL_PLANS> MEAL_PLANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM_ASSIGNED> ROOM_ASSIGNED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAREGIVER_ASSIGN_ELDER> CAREGIVER_ASSIGN_ELDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ELDER_DEATH> ELDER_DEATH { get; set; }
    }
}
