//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELDER_DEATH
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_DEATH { get; set; }
        public Nullable<System.TimeSpan> TIME_OF_DEATH { get; set; }
        public string CAUSE_OF_DEATH { get; set; }
        public string PLACE_OF_DEATH { get; set; }
        public string REPORTED_BY { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> ENTER_DATE { get; set; }
    
        public virtual ELDER ELDER { get; set; }
    }
}
