//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<int> CAREGIVER_ID { get; set; }
        public string FEEDBACK_TYPE { get; set; }
        public string FEEDBACK_DESC { get; set; }
        public string ADMIN_REPLY { get; set; }
        public Nullable<System.DateTime> REPLY_DATE { get; set; }
        public Nullable<System.DateTime> SUBMITED_DATE { get; set; }
        public string FEEDBACK_ENTERED_USE { get; set; }
    
        public virtual CAREGIVER CAREGIVER { get; set; }
        public virtual ELDER ELDER { get; set; }
    }
}
