//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLUCODE_READING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GLUCODE_READING()
        {
            this.GLUCOSE_READING_REPORT = new HashSet<GLUCOSE_READING_REPORT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<System.DateTime> READING_DATE { get; set; }
        public Nullable<decimal> GLUCOSE_LEVEL { get; set; }
        public string RECORDED_BY { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string SOURCE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ELDER ELDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLUCOSE_READING_REPORT> GLUCOSE_READING_REPORT { get; set; }
    }
}
