//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLUCOSE_READING_REPORT
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<int> GLUCODE_READING_ID { get; set; }
        public Nullable<System.DateTime> REPORT_UPLOAD_DATE { get; set; }
        public string REPORT { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual ELDER ELDER { get; set; }
        public virtual GLUCODE_READING GLUCODE_READING { get; set; }
    }
}
