//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROCERY_ITEM_CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROCERY_ITEM_CATEGORY()
        {
            this.GROCERY_ITEMS = new HashSet<GROCERY_ITEMS>();
        }
    
        public int ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROCERY_ITEMS> GROCERY_ITEMS { get; set; }
    }
}
