//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROCERY_ITEM_NUTRICIANTS
    {
        public int ID { get; set; }
        public Nullable<int> GROCERY_ITEMS_ID { get; set; }
        public Nullable<decimal> CALORIES_kcal { get; set; }
        public Nullable<decimal> PROTEIN { get; set; }
        public Nullable<decimal> CARBS { get; set; }
        public Nullable<decimal> SUGAR { get; set; }
        public Nullable<decimal> FIBER { get; set; }
        public Nullable<decimal> FAT_TOTAL { get; set; }
        public Nullable<decimal> FAT_SATURED { get; set; }
        public Nullable<decimal> CHOLESTROL { get; set; }
        public Nullable<decimal> SODIUM { get; set; }
        public Nullable<decimal> POTESSIUM { get; set; }
        public Nullable<decimal> IRON { get; set; }
        public Nullable<decimal> VITAMIN_A { get; set; }
        public Nullable<decimal> VITAMIN_C { get; set; }
    
        public virtual GROCERY_ITEMS GROCERY_ITEMS { get; set; }
    }
}
