//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROCERY_ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROCERY_ITEMS()
        {
            this.DONETION_EVENT_ITEMS = new HashSet<DONETION_EVENT_ITEMS>();
            this.GROCERY_ITEM_NUTRICIANTS = new HashSet<GROCERY_ITEM_NUTRICIANTS>();
            this.MEAL_PLANS_ITEMS = new HashSet<MEAL_PLANS_ITEMS>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string BRAND { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PICTURE { get; set; }
        public string FOOD_GROUP { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string CREATE_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONETION_EVENT_ITEMS> DONETION_EVENT_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROCERY_ITEM_NUTRICIANTS> GROCERY_ITEM_NUTRICIANTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL_PLANS_ITEMS> MEAL_PLANS_ITEMS { get; set; }
        public virtual GROCERY_ITEM_CATEGORY GROCERY_ITEM_CATEGORY { get; set; }
    }
}
