//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_ALERT
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public string ALERT_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUGGESTED_ACTION { get; set; }
        public Nullable<System.DateTime> NOTIFICATION_DATE { get; set; }
    
        public virtual ELDER ELDER { get; set; }
    }
}
