//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEAL_PLANS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEAL_PLANS()
        {
            this.MEAL_PLANS_ITEMS = new HashSet<MEAL_PLANS_ITEMS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<System.DateTime> PLAN_DATE { get; set; }
        public string PLAN_TYPE { get; set; }
        public Nullable<int> RECOMENDED_DOC_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual ELDER ELDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEAL_PLANS_ITEMS> MEAL_PLANS_ITEMS { get; set; }
    }
}
