//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEAL_PLANS_ITEMS
    {
        public int ID { get; set; }
        public Nullable<int> MEAL_PLAN_ID { get; set; }
        public Nullable<int> GROCEY_ID { get; set; }
        public Nullable<decimal> QUANTITY_IN_GRAMS { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
    
        public virtual GROCERY_ITEMS GROCERY_ITEMS { get; set; }
        public virtual MEAL_PLANS MEAL_PLANS { get; set; }
    }
}
