//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ELDER
    {
        public int ID { get; set; }
        public string ELDER_CODE { get; set; }
        public string FULL_NAME { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string GENDER { get; set; }
        public string CONTACT_NO { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<int> IS_DEAD { get; set; }
        public string PROFIL_PIC { get; set; }
        public string ROOM_NUMBER { get; set; }
        public Nullable<decimal> CURRENT_SUGAR_LEVEL { get; set; }
        public Nullable<System.DateTime> CURRENT_SUGAR_LEVEL_ENTER_DATE { get; set; }
        public Nullable<int> IS_DIABITCS { get; set; }
        public string E_GURDIAN_CODE { get; set; }
        public string G_FULL_NAME { get; set; }
        public string RELATIONSHIP { get; set; }
        public string G_CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
    }
}
