//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ELDER_BLOOD_RPT
    {
        public int ID { get; set; }
        public Nullable<int> ELDER_ID { get; set; }
        public Nullable<System.DateTime> READING_DATE { get; set; }
        public Nullable<decimal> GLUCOSE_LEVEL { get; set; }
        public string RECORDED_BY { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string SOURCE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> REPORT_UPLOAD_DATE { get; set; }
        public string REPORT { get; set; }
    }
}
