//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELDER_NUTRICIANTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MEALS
    {
        public string CATEGORY_NAME { get; set; }
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY_ID { get; set; }
        public string BRAND { get; set; }
        public string BARCODE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PICTURE { get; set; }
        public string FOOD_GROUP { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DOC_ID { get; set; }
        public string CREATE_BY { get; set; }
        public string TYPE { get; set; }
    }
}
